### ISSUE TITLE
failed to compile on visual studio 2013/version 12.0.40629.00 Update 5

### ISSUE THREAD

**Issue by 7starsea** [vincentlaucsb/csv-parser#23]
Error message:
internal\csv_row.hpp(204): error C2440: '<function-style-cast>' : cannot convert from 'csv::string_view' to 'std::string'          No constructor could take the source type, or constructor overload resolution was ambiguous

**Comment by 7starsea** [comment]
There is another compiling problem for vs2013 when constructing std::string from string_view in 
csv_row.hpp:Line 204 and csv_row.cpp:Line 96 and csv_reader.cpp:Line 346.

We could fix this by using constructor std::string( sv.data(), sv.size() ) where sv is an instance of string_view.

Thanks.

**Comment by vincentlaucsb** [comment]
Can you confirm that these changes work? I'm using Visual Studio 2017 and would prefer not to have to install 2013 as well.

**Comment by 7starsea** [comment]
Yes, I confirm that using constructor std::string( sv.data(), sv.size() ) works on vs2013.

However, there is another error on vs2013: "concrt.h(1224): error c2061: syntax error : identifier 'hresult',
stackoverflow suggested checking "circular dependency of header files", and I cleaned some non-necessary include's. It worked for me now.

Thanks.
